### ISSUE TITLE
no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no no

### ISSUE THREAD

**Issue by TheoBuzz** [Tschipp/SubnauticRedstone#2]
this is stupid forge is already good this is bad fuck you delete this shit ur fabruc sucks use forge mother fuckers fabric sucks forge is perfect awesome good for mod needs no fabric is hacks hacks HACKS mixins stupid kill your self im gay btw

**Comment by Tschipp** [comment]
Thank you for clarifying that you're gay.

**Comment by Tschipp** [comment]
https://user-images.githubusercontent.com/63550306/84594223-1f5d1780-ae51-11ea-989e-9685f8792b76.png
